### ISSUE TITLE
希望做一个wordpress的主题包

### ISSUE THREAD

**Issue by liudandandear** [HelipengTony/ouorz-next#1]
希望大佬能辛苦做一个wordpress的主题包，能直接上传就能用的那种。

**Comment by HelipengTony** [comment]
目前暂不考虑单独做成主题

你可以使用 Tony 主题:
https://github.com/helipengTony/tony

**Comment by liudandandear** [comment]
> 目前暂不考虑单独打造主题
> 
> 你可以使用Tony主题：[https](https://github.com/helipengTony/tony) :
> [//github.com/helipengTony/tony](https://github.com/helipengTony/tony)

嗯呢，已经在使用了
