### ISSUE TITLE
Unhandled Runtime Error TypeError: appId must be a string

### ISSUE THREAD

**Issue by yanbohon** [HelipengTony/ouorz-next#96]
yarn run dev后打开页面报错
<img width="953" alt="截屏2021-06-11 下午2 47 47" src="https://user-images.githubusercontent.com/26356290/121643205-24848f00-cac4-11eb-97ae-ffb0f7c00bd0.png">

**Comment by yanbohon** [comment]
<img width="864" alt="截屏2021-06-11 下午3 37 31" src="https://user-images.githubusercontent.com/26356290/121649341-10905b80-cacb-11eb-9c84-e03f6098ba68.png">

**Comment by HelipengTony** [comment]
`appId` is used by the built-in comment system ([Nexment](https://github.com/HelipengTony/nexment)); for safety reasons, it has been stored as an environment variable. You might want to read the source code and find out how it is used first, then adjust for your own needs. Thanks.
Gonna set this as invalid for now, good luck.
